2017-12-03 09:55:27.842 -02 [63259] LOG:  listening on IPv6 address "::1", port 5432
2017-12-03 09:55:27.842 -02 [63259] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-03 09:55:27.843 -02 [63259] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-03 09:55:27.844 -02 [63259] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-03 09:55:27.862 -02 [63260] LOG:  database system was shut down at 2017-12-03 09:55:21 -02
2017-12-03 09:55:27.874 -02 [63259] LOG:  database system is ready to accept connections
2017-12-03 09:55:48.750 -02 [63259] LOG:  received fast shutdown request
2017-12-03 09:55:48.751 -02 [63259] LOG:  aborting any active transactions
2017-12-03 09:55:48.752 -02 [63259] LOG:  worker process: logical replication launcher (PID 63266) exited with exit code 1
2017-12-03 09:55:48.752 -02 [63261] LOG:  shutting down
2017-12-03 09:55:48.764 -02 [63259] LOG:  database system is shut down
2017-12-03 09:56:34.339 -02 [63489] LOG:  listening on IPv6 address "::1", port 5432
2017-12-03 09:56:34.339 -02 [63489] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-03 09:56:34.339 -02 [63489] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-03 09:56:34.340 -02 [63489] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-03 09:56:34.357 -02 [63490] LOG:  database system was shut down at 2017-12-03 09:55:48 -02
2017-12-03 09:56:34.364 -02 [63489] LOG:  database system is ready to accept connections
2017-12-03 09:56:40.697 -02 [63489] LOG:  received fast shutdown request
2017-12-03 09:56:40.697 -02 [63489] LOG:  aborting any active transactions
2017-12-03 09:56:40.699 -02 [63489] LOG:  worker process: logical replication launcher (PID 63496) exited with exit code 1
2017-12-03 09:56:40.699 -02 [63491] LOG:  shutting down
2017-12-03 09:56:40.712 -02 [63489] LOG:  database system is shut down
2017-12-03 09:57:33.607 -02 [63655] LOG:  listening on IPv6 address "::1", port 5432
2017-12-03 09:57:33.607 -02 [63655] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-03 09:57:33.607 -02 [63655] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-03 09:57:33.609 -02 [63655] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-03 09:57:33.625 -02 [63656] LOG:  database system was shut down at 2017-12-03 09:56:40 -02
2017-12-03 09:57:33.632 -02 [63655] LOG:  database system is ready to accept connections
2017-12-03 10:04:22.666 -02 [64280] ERROR:  syntax error at or near "CREATE" at character 74
2017-12-03 10:04:22.666 -02 [64280] STATEMENT:  CREATE TABLE events(id serial PRIMARY KEY, type varchar(30), data jsonb)
	CREATE TABLE
	CREATE DATABASE minibank
	CREATE DATABASE minibank
	dl
	CREATE DATABASE minibank;
2017-12-03 10:07:52.339 -02 [64677] ERROR:  invalid input syntax for integer: "Create User" at character 27
2017-12-03 10:07:52.339 -02 [64677] STATEMENT:  INSERT INTO events VALUES('Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:07:52.353 -02 [64678] ERROR:  invalid input syntax for integer: "Create User" at character 27
2017-12-03 10:07:52.353 -02 [64678] STATEMENT:  INSERT INTO events VALUES('Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:14:52.686 -02 [65131] ERROR:  relation "minibank" does not exist at character 15
2017-12-03 10:14:52.686 -02 [65131] STATEMENT:  SELECT * from minibank
	;
2017-12-03 10:14:55.246 -02 [65131] ERROR:  relation "minibank" does not exist at character 15
2017-12-03 10:14:55.246 -02 [65131] STATEMENT:  SELECT * from minibank;
2017-12-03 10:15:02.070 -02 [65131] ERROR:  relation "minibank" does not exist at character 15
2017-12-03 10:15:02.070 -02 [65131] STATEMENT:  SELECT * FROM minibank;
2017-12-03 10:16:04.324 -02 [65200] ERROR:  syntax error at or near "|" at character 1
2017-12-03 10:16:04.324 -02 [65200] STATEMENT:  | {"user": {"uid": 1, "name": "Paulo", "accounts": [], "is_person": true}}
	;
2017-12-03 10:16:49.660 -02 [65200] ERROR:  syntax error at or near "*" at character 8
2017-12-03 10:16:49.660 -02 [65200] STATEMENT:  DELETE * FROM events
	;
2017-12-03 10:16:52.408 -02 [65200] ERROR:  syntax error at or near "*" at character 8
2017-12-03 10:16:52.408 -02 [65200] STATEMENT:  DELETE * FROM events;
2017-12-03 10:16:57.891 -02 [65200] ERROR:  syntax error at or near "ALL" at character 8
2017-12-03 10:16:57.891 -02 [65200] STATEMENT:  DELETE ALL FROM events;
2017-12-03 10:19:33.353 -02 [65443] ERROR:  INSERT has more target columns than expressions at character 30
2017-12-03 10:19:33.353 -02 [65443] STATEMENT:  INSERT INTO events(id, type, data) VALUES('1,Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:19:33.366 -02 [65444] ERROR:  INSERT has more target columns than expressions at character 30
2017-12-03 10:19:33.366 -02 [65444] STATEMENT:  INSERT INTO events(id, type, data) VALUES('1,Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:23:41.898 -02 [65674] ERROR:  invalid input syntax for integer: "1,Create User" at character 27
2017-12-03 10:23:41.898 -02 [65674] STATEMENT:  INSERT INTO events VALUES('1,Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:23:41.911 -02 [65675] ERROR:  invalid input syntax for integer: "1,Create User" at character 27
2017-12-03 10:23:41.911 -02 [65675] STATEMENT:  INSERT INTO events VALUES('1,Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:24:06.326 -02 [65751] ERROR:  duplicate key value violates unique constraint "events_pkey"
2017-12-03 10:24:06.326 -02 [65751] DETAIL:  Key (id)=(1) already exists.
2017-12-03 10:24:06.326 -02 [65751] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:26:16.886 -02 [65882] ERROR:  syntax error at or near "IF" at character 1
2017-12-03 10:26:16.886 -02 [65882] STATEMENT:  IF NOT EXISTS(SELECT * FROM events WHERE id = 1) INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:26:16.899 -02 [65883] ERROR:  syntax error at or near "IF" at character 1
2017-12-03 10:26:16.899 -02 [65883] STATEMENT:  IF NOT EXISTS(SELECT * FROM events WHERE id = 1) INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-03 10:27:38.018 -02 [65990] ERROR:  syntax error at or near "IF" at character 1
2017-12-03 10:27:38.018 -02 [65990] STATEMENT:  IF NOT EXISTS(SELECT * FROM events WHERE id = 1)
	INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
	ENDIF
2017-12-03 10:27:38.032 -02 [65991] ERROR:  syntax error at or near "IF" at character 1
2017-12-03 10:27:38.032 -02 [65991] STATEMENT:  IF NOT EXISTS(SELECT * FROM events WHERE id = 1)
	INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
	ENDIF
2017-12-03 10:29:40.772 -02 [66119] ERROR:  syntax error at or near "UPDATE" at character 132
2017-12-03 10:29:40.772 -02 [66119] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT UPDATE
2017-12-03 10:29:40.783 -02 [66120] ERROR:  syntax error at or near "UPDATE" at character 132
2017-12-03 10:29:40.783 -02 [66120] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT UPDATE
2017-12-03 10:29:56.432 -02 [66190] ERROR:  syntax error at end of input at character 141
2017-12-03 10:29:56.432 -02 [66190] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE
2017-12-03 10:29:56.444 -02 [66191] ERROR:  syntax error at end of input at character 141
2017-12-03 10:29:56.444 -02 [66191] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE
2017-12-04 00:11:32.480 -02 [91981] FATAL:  lock file "postmaster.pid" already exists
2017-12-04 00:11:32.480 -02 [91981] HINT:  Is another postmaster (PID 63655) running in data directory "/Users/valente/Dropbox/Programas/MiniBank/MiniBank/Domains/Database/PostgresDatabase"?
2017-12-04 00:13:07.627 -02 [63655] LOG:  received fast shutdown request
2017-12-04 00:13:07.628 -02 [63655] LOG:  aborting any active transactions
2017-12-04 00:13:07.632 -02 [63655] LOG:  worker process: logical replication launcher (PID 63662) exited with exit code 1
2017-12-04 00:13:07.633 -02 [63657] LOG:  shutting down
2017-12-04 00:13:07.738 -02 [63655] LOG:  database system is shut down
2017-12-05 00:37:28.876 -02 [17861] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 00:37:28.879 -02 [17861] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 00:37:28.879 -02 [17861] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 00:37:28.881 -02 [17861] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 00:37:28.910 -02 [17862] LOG:  database system was shut down at 2017-12-04 00:13:07 -02
2017-12-05 00:37:28.933 -02 [17861] LOG:  database system is ready to accept connections
2017-12-05 00:40:26.826 -02 [18118] FATAL:  database "valente" does not exist
2017-12-05 00:40:45.117 -02 [18150] FATAL:  database "MiniBank/Domains/Database/PostgresDatabase" does not exist
2017-12-05 00:40:50.556 -02 [18181] FATAL:  database "MiniBank/Domains/Database/PostgresDatabase" does not exist
2017-12-05 00:40:52.287 -02 [18212] FATAL:  database "MiniBank/Domains/Database/PostgresDatabase/" does not exist
2017-12-05 00:40:53.944 -02 [18243] FATAL:  database "MiniBank/Domains/Database/PostgresDatabase" does not exist
2017-12-05 00:43:10.793 -02 [18276] ERROR:  syntax error at or near "dt" at character 1
2017-12-05 00:43:10.793 -02 [18276] STATEMENT:  dt
	SELECT * FROM TABLE events
	SELECT * FROM TABLE events
	;
2017-12-05 00:43:19.973 -02 [18276] ERROR:  syntax error at or near "TABLE" at character 15
2017-12-05 00:43:19.973 -02 [18276] STATEMENT:  SELECT * FROM TABLE events;
2017-12-05 00:43:22.243 -02 [18276] ERROR:  syntax error at or near "TABLE" at character 15
2017-12-05 00:43:22.243 -02 [18276] STATEMENT:  SELECT * FROM TABLE events;
2017-12-05 00:44:09.206 -02 [18355] ERROR:  relation "events" does not exist at character 13
2017-12-05 00:44:09.206 -02 [18355] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO NOTHING
2017-12-05 00:44:09.219 -02 [18356] ERROR:  relation "events" does not exist at character 13
2017-12-05 00:44:09.219 -02 [18356] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO NOTHING
2017-12-05 00:45:22.862 -02 [18423] ERROR:  syntax error at end of input at character 141
2017-12-05 00:45:22.862 -02 [18423] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE
2017-12-05 00:45:22.872 -02 [18424] ERROR:  syntax error at end of input at character 141
2017-12-05 00:45:22.872 -02 [18424] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE
2017-12-05 00:48:03.405 -02 [18494] ERROR:  syntax error at or near "(" at character 152
2017-12-05 00:48:03.405 -02 [18494] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-05 00:48:03.414 -02 [18495] ERROR:  syntax error at or near "(" at character 152
2017-12-05 00:48:03.414 -02 [18495] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-05 00:48:57.441 -02 [18558] ERROR:  syntax error at or near "type" at character 151
2017-12-05 00:48:57.441 -02 [18558] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET id=1 type='Create User' data='{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-05 00:48:57.452 -02 [18559] ERROR:  syntax error at or near "type" at character 151
2017-12-05 00:48:57.452 -02 [18559] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET id=1 type='Create User' data='{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-05 00:49:15.246 -02 [18626] ERROR:  syntax error at or near ")" at character 251
2017-12-05 00:49:15.246 -02 [18626] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET id=1, type='Create User', data='{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-05 00:49:15.257 -02 [18627] ERROR:  syntax error at or near ")" at character 251
2017-12-05 00:49:15.257 -02 [18627] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET id=1, type='Create User', data='{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}')
2017-12-05 00:49:52.090 -02 [18690] ERROR:  ON CONFLICT DO UPDATE requires inference specification or constraint name at character 120
2017-12-05 00:49:52.090 -02 [18690] HINT:  For example, ON CONFLICT (column_name).
2017-12-05 00:49:52.090 -02 [18690] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET id=1, type='Create User', data='{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}'
2017-12-05 00:49:52.102 -02 [18691] ERROR:  ON CONFLICT DO UPDATE requires inference specification or constraint name at character 120
2017-12-05 00:49:52.102 -02 [18691] HINT:  For example, ON CONFLICT (column_name).
2017-12-05 00:49:52.102 -02 [18691] STATEMENT:  INSERT INTO events VALUES(1,'Create User', '{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}') ON CONFLICT DO UPDATE SET id=1, type='Create User', data='{"user": {"is_person": true, "accounts": [], "uid": 1, "name": "Paulo"}}'
2017-12-05 14:29:43.903 -02 [22236] FATAL:  lock file "postmaster.pid" already exists
2017-12-05 14:29:43.903 -02 [22236] HINT:  Is another postmaster (PID 17861) running in data directory "/Users/valente/Dropbox/Programas/MiniBank/MiniBank/Domains/Database/PostgresDatabase"?
2017-12-05 14:29:51.787 -02 [22303] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:29:51.787 -02 [22303] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:29:51.787 -02 [22303] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:29:51.788 -02 [22303] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:29:51.818 -02 [22304] LOG:  database system was shut down at 2017-12-05 14:29:50 -02
2017-12-05 14:29:51.818 -02 [22304] LOG:  invalid record length at 0/163D520: wanted 24, got 0
2017-12-05 14:29:51.818 -02 [22304] LOG:  invalid primary checkpoint record
2017-12-05 14:29:51.819 -02 [22304] LOG:  using previous checkpoint record at 0/163CDB0
2017-12-05 14:29:51.823 -02 [22304] LOG:  database system was not properly shut down; automatic recovery in progress
2017-12-05 14:29:51.824 -02 [22304] FATAL:  could not open directory "pg_stat_tmp": No such file or directory
2017-12-05 14:29:51.824 -02 [22303] LOG:  startup process (PID 22304) exited with exit code 1
2017-12-05 14:29:51.824 -02 [22303] LOG:  aborting startup due to startup process failure
2017-12-05 14:29:51.827 -02 [22303] LOG:  database system is shut down
2017-12-05 14:30:16.098 -02 [22369] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:30:16.098 -02 [22369] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:30:16.098 -02 [22369] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:30:16.099 -02 [22369] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:30:16.118 -02 [22370] LOG:  database system was interrupted while in recovery at 2017-12-05 14:29:51 -02
2017-12-05 14:30:16.118 -02 [22370] HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
2017-12-05 14:30:17.224 -02 [22370] LOG:  database system was not properly shut down; automatic recovery in progress
2017-12-05 14:30:17.225 -02 [22370] FATAL:  could not open directory "pg_stat_tmp": No such file or directory
2017-12-05 14:30:17.225 -02 [22369] LOG:  startup process (PID 22370) exited with exit code 1
2017-12-05 14:30:17.225 -02 [22369] LOG:  aborting startup due to startup process failure
2017-12-05 14:30:17.227 -02 [22369] LOG:  database system is shut down
2017-12-05 14:31:16.014 -02 [22651] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:31:16.014 -02 [22651] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:31:16.014 -02 [22651] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:31:16.016 -02 [22651] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:31:16.041 -02 [22652] LOG:  database system was interrupted while in recovery at 2017-12-05 14:30:17 -02
2017-12-05 14:31:16.041 -02 [22652] HINT:  This probably means that some data is corrupted and you will have to use the last backup for recovery.
2017-12-05 14:31:16.513 -02 [22652] LOG:  database system was not properly shut down; automatic recovery in progress
2017-12-05 14:31:16.515 -02 [22652] FATAL:  could not open directory "pg_stat_tmp": No such file or directory
2017-12-05 14:31:16.516 -02 [22651] LOG:  startup process (PID 22652) exited with exit code 1
2017-12-05 14:31:16.516 -02 [22651] LOG:  aborting startup due to startup process failure
2017-12-05 14:31:16.517 -02 [22651] LOG:  database system is shut down
2017-12-05 14:34:11.721 -02 [23005] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:34:11.721 -02 [23005] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:34:11.721 -02 [23005] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:34:11.723 -02 [23005] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:34:11.740 -02 [23006] LOG:  database system was shut down at 2017-12-05 14:33:55 -02
2017-12-05 14:34:11.745 -02 [23005] LOG:  database system is ready to accept connections
2017-12-05 14:34:19.378 -02 [23043] FATAL:  database "minibank" does not exist
2017-12-05 14:34:22.450 -02 [23074] FATAL:  database "minibank" does not exist
2017-12-05 14:35:05.563 -02 [23106] FATAL:  database "valente" does not exist
2017-12-05 14:35:12.590 -02 [23137] FATAL:  database "valente" does not exist
2017-12-05 14:35:19.739 -02 [23168] FATAL:  database "valente" does not exist
2017-12-05 14:35:38.497 -02 [23199] FATAL:  database "valente" does not exist
2017-12-05 14:35:45.570 -02 [23233] FATAL:  lock file "postmaster.pid" already exists
2017-12-05 14:35:45.570 -02 [23233] HINT:  Is another postmaster (PID 23005) running in data directory "/Users/valente/Dropbox/Programas/MiniBank/MiniBank/Domains/Database/PostgresDatabase"?
2017-12-05 14:35:48.338 -02 [23265] FATAL:  database "valente" does not exist
2017-12-05 14:35:59.429 -02 [23005] LOG:  received fast shutdown request
2017-12-05 14:35:59.430 -02 [23005] LOG:  aborting any active transactions
2017-12-05 14:35:59.431 -02 [23005] LOG:  worker process: logical replication launcher (PID 23012) exited with exit code 1
2017-12-05 14:35:59.431 -02 [23007] LOG:  shutting down
2017-12-05 14:35:59.473 -02 [23005] LOG:  database system is shut down
2017-12-05 14:36:03.291 -02 [23362] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:36:03.291 -02 [23362] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:36:03.291 -02 [23362] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:36:03.293 -02 [23362] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:36:03.312 -02 [23363] LOG:  database system was shut down at 2017-12-05 14:35:59 -02
2017-12-05 14:36:03.324 -02 [23362] LOG:  database system is ready to accept connections
2017-12-05 14:36:06.103 -02 [23400] FATAL:  database "valente" does not exist
2017-12-05 14:36:12.427 -02 [23431] FATAL:  database "valente" does not exist
2017-12-05 14:36:51.947 -02 [23465] FATAL:  database "minibank" does not exist
2017-12-05 14:37:08.615 -02 [23496] FATAL:  database "valente" does not exist
2017-12-05 14:39:08.205 -02 [23749] FATAL:  database "minibank" does not exist
2017-12-05 14:39:46.825 -02 [23809] FATAL:  role "postgres" does not exist
2017-12-05 14:41:09.005 -02 [23716] ERROR:  syntax error at or near "CREATE" at character 59
2017-12-05 14:41:09.005 -02 [23716] STATEMENT:  CREATE ROLE test_user WITH LOGIN PASSWORD 'test_password'
	CREATE ROLE test_user WITH LOGIN PASSWORD 'test_password';
2017-12-05 14:42:35.758 -02 [23873] FATAL:  database "minibank" does not exist
2017-12-05 14:46:32.881 -02 [23716] ERROR:  syntax error at or near "TABLE" at character 15
2017-12-05 14:46:32.881 -02 [23716] STATEMENT:  SELECT * FROM TABLE events
	;
2017-12-05 14:46:35.198 -02 [23716] ERROR:  syntax error at or near "TABLE" at character 15
2017-12-05 14:46:35.198 -02 [23716] STATEMENT:  SELECT * FROM TABLE events;
2017-12-05 14:47:06.280 -02 [23362] LOG:  received fast shutdown request
2017-12-05 14:47:06.281 -02 [23362] LOG:  aborting any active transactions
2017-12-05 14:47:06.282 -02 [23362] LOG:  worker process: logical replication launcher (PID 23369) exited with exit code 1
2017-12-05 14:47:06.283 -02 [23364] LOG:  shutting down
2017-12-05 14:47:06.296 -02 [23362] LOG:  database system is shut down
2017-12-05 14:48:57.086 -02 [1259] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:48:57.088 -02 [1259] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:48:57.089 -02 [1259] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:48:57.090 -02 [1259] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:48:57.123 -02 [1260] LOG:  database system was shut down at 2017-12-05 14:47:06 -02
2017-12-05 14:48:57.141 -02 [1259] LOG:  database system is ready to accept connections
2017-12-05 14:49:15.856 -02 [1259] LOG:  received fast shutdown request
2017-12-05 14:49:15.856 -02 [1259] LOG:  aborting any active transactions
2017-12-05 14:49:15.857 -02 [1259] LOG:  worker process: logical replication launcher (PID 1266) exited with exit code 1
2017-12-05 14:49:15.857 -02 [1261] LOG:  shutting down
2017-12-05 14:49:15.884 -02 [1259] LOG:  database system is shut down
2017-12-05 14:51:36.807 -02 [1523] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:51:36.807 -02 [1523] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:51:36.807 -02 [1523] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:51:36.808 -02 [1523] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:51:36.824 -02 [1524] LOG:  database system was shut down at 2017-12-05 14:49:15 -02
2017-12-05 14:51:36.830 -02 [1523] LOG:  database system is ready to accept connections
2017-12-05 14:52:26.284 -02 [1523] LOG:  received fast shutdown request
2017-12-05 14:52:26.284 -02 [1523] LOG:  aborting any active transactions
2017-12-05 14:52:26.284 -02 [1564] FATAL:  terminating connection due to administrator command
2017-12-05 14:52:26.284 -02 [1562] FATAL:  terminating connection due to administrator command
2017-12-05 14:52:26.285 -02 [1523] LOG:  worker process: logical replication launcher (PID 1530) exited with exit code 1
2017-12-05 14:52:26.286 -02 [1525] LOG:  shutting down
2017-12-05 14:52:26.302 -02 [1523] LOG:  database system is shut down
2017-12-05 14:53:48.079 -02 [2374] LOG:  listening on IPv6 address "::1", port 5432
2017-12-05 14:53:48.079 -02 [2374] LOG:  listening on IPv6 address "fe80::1%lo0", port 5432
2017-12-05 14:53:48.079 -02 [2374] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2017-12-05 14:53:48.080 -02 [2374] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2017-12-05 14:53:48.096 -02 [2375] LOG:  database system was shut down at 2017-12-05 14:52:26 -02
2017-12-05 14:53:48.102 -02 [2374] LOG:  database system is ready to accept connections
2017-12-05 15:00:40.960 -02 [2537] FATAL:  lock file "postmaster.pid" already exists
2017-12-05 15:00:40.960 -02 [2537] HINT:  Is another postmaster (PID 2374) running in data directory "/Users/valente/Dropbox/Programas/MiniBank/MiniBank/Domains/Database/PostgresDatabase"?
2017-12-05 15:05:29.633 -02 [2972] FATAL:  lock file "postmaster.pid" already exists
2017-12-05 15:05:29.633 -02 [2972] HINT:  Is another postmaster (PID 2374) running in data directory "/Users/valente/Dropbox/Programas/MiniBank/MiniBank/Domains/Database/PostgresDatabase"?
2017-12-05 15:07:55.774 -02 [3234] FATAL:  lock file "postmaster.pid" already exists
2017-12-05 15:07:55.774 -02 [3234] HINT:  Is another postmaster (PID 2374) running in data directory "/Users/valente/Dropbox/Programas/MiniBank/MiniBank/Domains/Database/PostgresDatabase"?
2017-12-05 15:18:23.219 -02 [2374] LOG:  received fast shutdown request
2017-12-05 15:18:23.220 -02 [2374] LOG:  aborting any active transactions
2017-12-05 15:18:23.220 -02 [2374] LOG:  worker process: logical replication launcher (PID 2381) exited with exit code 1
2017-12-05 15:18:23.221 -02 [2376] LOG:  shutting down
2017-12-05 15:18:23.235 -02 [2374] LOG:  database system is shut down
